window.$ = window.jQuery = $ = require 'jquery'
transition = require './transition'
alert = require './alert'
button = require './button'
carousel = require './carousel'
collapse = require './collapse'
dropdown = require './dropdown'
modal = require './modal'
tooltip = require './tooltip'
popover = require './popover'
scrollspy = require './scrollspy'
tab = require './tab'
affix = require './affix'